GET http://localhost:3001/api/persons

###
GET http://localhost:3001/info

###
GET http://localhost:3001/api/persons/621446ef2459fc6f617e69c9

###
DELETE http://localhost:3001/api/persons/621ff21ac6f0aaabfda14bf4

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name":"Yerik",
    "number":"074-1852963"
}

###
GET http://localhost:3001/api/invalid

###
GET http://localhost:3001/api/persons/SomeOtherStuff